# Generated by Django 3.2.16 on 2022-12-03 14:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('eircode', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=20)),
                ('acc_created_on', models.DateTimeField(auto_now_add=True)),
                ('acc_updated_on', models.DateTimeField(auto_now=True)),
                ('is_service_provider', models.BooleanField(default=False)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Kennel Boarding'), (2, 'Pet Setting'), (3, 'Dog walking')])),
                ('total_occupancy', models.IntegerField()),
                ('price_per_service', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('has_fenced_garden', models.BooleanField(default=False)),
                ('non_smoking', models.BooleanField(default=False)),
                ('pet_allowed_in_house', models.BooleanField(default=False)),
                ('owner_has_dog', models.BooleanField(default=False)),
                ('owner_has_cat', models.BooleanField(default=False)),
                ('owner_has_children', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviceprovider', to='profiles.userprofile')),
            ],
        ),
    ]
