# Generated by Django 3.2.16 on 2022-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', 'I have a query on a Booking'), ('2', 'I have query on becoming Service Provider'), ('3', 'All Other Queries')], default='1', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=70)),
                ('creation_date', models.DateField(auto_now=True)),
                ('is_replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
