# Generated by Django 3.2.16 on 2022-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=254)),
                ('service_length', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sub_heading', models.CharField(max_length=254)),
                ('detail_1', models.CharField(max_length=254)),
                ('detail_2', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('additional_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
