# Generated by Django 3.2.16 on 2022-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
